Update index.md
mserykh/github-pages-with-jekyll pull request #3
Opened 2020-12-22 12:38 UTC by mserykh

2020-12-22 12:40 UTC, mserykh reviewed
Looks good

2020-12-27 12:53 UTC, dev-experience commented on index.md
> +I am Marie Serykh and am aiming to become a Sofrwear Developer. To be precise a Front-End Developer.
Please fix the typo

2020-12-27 12:53 UTC, dev-experience requested changes
Please check my comment.

2020-12-29 15:54 UTC, mserykh commented on index.md
> +I am Marie Serykh and am aiming to become a Sofrwear Developer. To be precise a Front-End Developer.
Done

2020-12-29 20:34 UTC, dev-experience approved these changes

2021-01-02 10:26 UTC, merged